### ISSUE TITLE
Won't play on Curse launcher

### ISSUE THREAD

**Issue by JoePalffy** [scalda/Survival-Stories-3#1]
I'm having a weird issue with this, it downloaded and installed, took about an hour but it did, but it won't start. I get as far as the minecraft launcher i hit play and it downloads a few small files quickly, the window disappears and then 3 seconds later it comes back with a new 4th tab open called Game Output and say this:

> [01:06:11] [main/INFO] [LaunchWrapper]: Loading tweak class name cpw.mods.fml.common.launcher.FMLTweaker
> [01:06:11] [main/INFO] [LaunchWrapper]: Using primary tweak class name cpw.mods.fml.common.launcher.FMLTweaker
> [01:06:11] [main/INFO] [LaunchWrapper]: Calling tweak class cpw.mods.fml.common.launcher.FMLTweaker
> [01:06:11] [main/INFO] [FML]: Forge Mod Loader version 7.99.39.1566 for Minecraft 1.7.10 loading
> [01:06:11] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_25, running on Windows 10:amd64:10.0, installed at C:\Curse\Minecraft\Install\runtime\jre-x64\1.8.0_25
> [01:06:11] [main/INFO] [FML]: [AppEng] Core Init
> [01:06:11] [main/WARN] [FML]: The coremod codechicken.core.launch.CodeChickenCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft

If i hit play it goes downloads a few small files real quick again, then goes away for 3 seconds and comes back to this and so on.
Tried using an older version of forge, it didn't help.

My only choice would be to try it on the FTB Launcher (the legacy one)

**Comment by scalda** [comment]
Need to assign at least 4-5GB ram, but yes try the FTB launcher, and then
get back to me

**Comment by JoePalffy** [comment]
tried the FTB Launcher same deal, but that only assigned it 2GB, Curse however gave it 4GB, same log/error message on FTB.
Assigned 8GB on both and still same deal, but maybe i have to restart the launchers for that to take effect ?
I'll try that tomorrow, it's way to late here.

**Comment by JoePalffy** [comment]
OK, tried it again today, with 8GB of ram allocated on the FTB Launcher and got this extra code

>[12:09:46] [DEBUG] Benchmark.logBenchAs:73: UnreadNews Init took 0 ms.
> [12:09:47] [INFO] ProcessMonitor.run:43: MC process exited. return value: -1073740791

With curse launcher at least the minecraft launcher started not with FTB.

**Comment by JoePalffy** [comment]
Found the same error code in a forum, apparently it might be a graphics driver issue, downloading the latest one right now. I'll get back with the results.

**Comment by JoePalffy** [comment]
OK, that seems to have fixed it. Turns out all modpacks were affected, but yours was the first (and only one) i tried since reinstalling windows 10. Sorry for wasting your time, but without your suggestion to increase ram i would have never fixed it.

**Comment by scalda** [comment]
That's great news glad i could help.
