### ISSUE TITLE
New world and yet not ?

### ISSUE THREAD

**Issue by JoePalffy** [scalda/Survival-Stories-3#2]
I just created a new world using seed 3251223 (biomes'o plenty, bonus chest on, cheats on) and upon checking the jorneymap a fairly large portion of the map is already explored and there is a death waypoint
![mwsnap 2017-02-03 14_25_51](https://cloud.githubusercontent.com/assets/14361452/22591384/ee003826-ea1c-11e6-96ef-e084b5707e28.png)

Let me know if there is any further info you need.
And i guess it's not a real issue, but how can this be ? i never played this modpack in fact i just reinstalled windows a week ago so any saves would have been deleted.

**Comment by scalda** [comment]
My best guess is that some of the client data didn't get removed when when
the pack was packaged up.

Just go to options and delete map information and delete way points.

Sorry for the inconvenience

Regards

Scalda

**Comment by JoePalffy** [comment]
Would that be in the Curse launcher on in the Minecraft launcher ? i don't see it anywhere.

**Comment by JoePalffy** [comment]
P.S. are boats supposed to be this buggy ? when i got out of my first one it dropped me 20 blocks away and i couldn't interact with it anymore, my 2nd one broke after traveling 10 blocks in open water, the 3rd one disappeared when i got out and the location where it was seems to have gotten corrupted, can't move through that space anymore.

**Comment by JoePalffy** [comment]
Oh, did you mean in Journey Map ?

**Comment by scalda** [comment]
I did mean Journey map. and boats are very buggy in 1.7.10 i'm afraid

**Comment by JoePalffy** [comment]
Just had a crash:

> EnderIO: Found the following problem(s) with your installation:
> * The RF API that is being used (1.7.10R1.1.0 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.10 from arcane_engineering-0.2.6.jar).

**Comment by JoePalffy** [comment]
And now all of a sudden my mouse behaves very lazily, it's like a drunk guy following the finger of the policeman, re-launching the map/world doesn't fix it.
I think i'm just gonna have to abandon this modpack.
