### ISSUE TITLE
missing recipe

### ISSUE THREAD

**Issue by egan566** [scalda/Survival-Stories-3#4]
been enjoying SS3 (v1.2.1), wanted to go tru all achievements. Seems recipe in buildcraft for iron gear is missing ?!

**Comment by Jo-Mamma75** [comment]
Probably need to add NoMoreRecipeConflicts because I assume the BC gear recipe conflicts with the TE one. Is that the case?

**Comment by egan566** [comment]
tks reply Jo-Mamma75 .. long time ago :)
TE = thermal expansion? I stopped playing SS3 it coz too many unloaded chunks .. switched to POL.
Resurrected old laptop to have a look SS3 .. sure, there are some conflicts reported after start, ignored it.
I will have a look at "conflicts" ...  ( will there be SS4 for minecraft v1.10 ?)
